version: "3"
services:
  wxgzh-api:
    image: beautyyu/python-selenium:latest
    command: sh -c "pip3 install -r requirements.txt && pip3 install waitress && python3 -m waitress server:app"
    restart: always
    ports:
      - 11459:8080
    working_dir: /app
    volumes:
      - .:/app
    environment:
      COOKIE_FILE: cookies.json
