version: "3"
services:
  wxgzh-api:
    image: beautyyu/python-selenium:latest
    command: sh -c "pip3 install -r requirements.txt && python3 listen.py"
    restart: always # 自启动
#    ports:
#      - 11459:11459 # 默认监听端口
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DELAY: 3 #平均延迟时间(秒). 可能降低被微信后台风控的概率
    network_mode: host
